### ISSUE TITLE
Generator needs to be updated with new route filename "desert_routes.rb"

### ISSUE THREAD

**Issue by nicholasjhenry** [pivotalexperimental/desert#1]
script/generate desert_plugin blog
      create  vendor/plugins/blog
      create  vendor/plugins/blog/app
      create  vendor/plugins/blog/app/controllers
      create  vendor/plugins/blog/app/helpers
      create  vendor/plugins/blog/app/models
      create  vendor/plugins/blog/app/views
      create  vendor/plugins/blog/config
      create  vendor/plugins/blog/config/routes.rb
No such file or directory - /Library/Ruby/Gems/1.8/gems/desert-0.5.0/generators/desert_plugin/templates/routes.rb

**Comment by bcaccinolo** [comment]
And the patch is here :)

diff --git a/generators/desert_plugin/desert_plugin_generator.rb b/generators/desert_plugin/desert_plugin_generator.rb
index 73122ce..0ef4066 100644
--- a/generators/desert_plugin/desert_plugin_generator.rb
+++ b/generators/desert_plugin/desert_plugin_generator.rb
@@ -13,7 +13,7 @@ class DesertPluginGenerator < Rails::Generator::NamedBase
       m.directory "vendor/plugins/#{file_name}/app/views"

```
   m.directory "vendor/plugins/#{file_name}/config"
```
-      m.template "routes.rb", "vendor/plugins/#{file_name}/config/routes.rb"
- ```
   m.template "desert_routes.rb", "vendor/plugins/#{file_name}/config/desert_routes.rb"
  ```
  
     m.map_route_from_plugin
  
     m.directory "vendor/plugins/#{file_name}/db"
